eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
spring:
  application:
    name: students
  config: optional:configserver:http://localhost:8090
  datasource:
    driver-class-name: org.postgresql.Driver
    password: "123"
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
